#!/usr/bin/env python3
"""Report the remaining legacy package/helper surface.

This is deliberately a report-only command. It is the cutover gate used
before deleting YunoHost compatibility code: a native package is only
classified as native when it has package.toml and no imperative lifecycle
scripts. The command has no host-side effects.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


LIFECYCLE_SCRIPTS = (
    "install",
    "upgrade",
    "remove",
    "backup",
    "restore",
    "change_url",
    "config",
    "check_process",
    "diagnosis",
)


def package_rows(root: Path) -> list[tuple[str, str, list[str]]]:
    rows: list[tuple[str, str, list[str]]] = []
    packages = root / "packages"
    if not packages.is_dir():
        return rows
    for package in sorted(path for path in packages.iterdir() if path.is_dir()):
        native = (package / "package.toml").is_file()
        legacy = (package / "manifest.json").is_file()
        scripts = sorted(name for name in LIFECYCLE_SCRIPTS if (package / "scripts" / name).is_file())
        if native and not scripts and not legacy:
            status = "native"
        elif native and not scripts:
            status = "native+legacy-metadata"
        elif legacy or scripts:
            status = "legacy"
        else:
            status = "unclassified"
        rows.append((package.name, status, scripts))
    return rows


def helper_summary(root: Path) -> tuple[int, int]:
    helper_dir = root / "forks" / "yunohost" / "helpers" / "helpers.v2.1.d"
    files = sorted(path for path in helper_dir.iterdir() if path.is_file()) if helper_dir.is_dir() else []
    functions = 0
    for path in files:
        text = path.read_text(encoding="utf-8", errors="replace")
        functions += len(re.findall(r"(?:^|\n)\s*(?:function\s+)?ynh_[A-Za-z0-9_]+\s*\(\)?\s*\{?", text))
    return len(files), functions


def render(root: Path) -> str:
    rows = package_rows(root)
    helper_files, helper_functions = helper_summary(root)
    counts = {status: sum(row[1] == status for row in rows) for status in {row[1] for row in rows}}
    lines = [
        "# Legacy Resource-Engine Inventory",
        "",
        "Generated by `tools/legacy_inventory.py`; this report is report-only and has no host-side effects.",
        "",
        f"- Packages scanned: {len(rows)}",
        f"- Native packages: {counts.get('native', 0)}",
        f"- Native packages with legacy metadata: {counts.get('native+legacy-metadata', 0)}",
        f"- Legacy packages: {counts.get('legacy', 0)}",
        f"- Helper domains/files: {helper_files}; exported `ynh_*` functions: {helper_functions}",
        "",
        "## Package cutover status",
        "",
        "| Package | Status | Imperative scripts |",
        "|---|---|---|",
    ]
    for name, status, scripts in rows:
        lines.append(f"| `{name}` | `{status}` | {', '.join(f'`{s}`' for s in scripts) or '—'} |")
    lines += [
        "",
        "## Removal decisions",
        "",
        "No helper or lifecycle surface is deleted by this command. The current tree still contains one legacy fixture package and YunoHost's host-level hooks import `/usr/share/yunohost/helpers`.",
        "",
        "The following can be removed only after the listed gates pass in the VM:",
        "",
        "| Surface | Gate |",
        "|---|---|",
        "| `helpers/helpers.v2.1.d/` and `helpers/helpers.v2.d` | No installed or supported package, backup hook, restore hook, or host hook sources the helper tree. |",
        "| `src/utils/legacy.py` | No package uses the legacy patch path; native packages are rejected before `yunohost.app`. |",
        "| `src/utils/resources.py` and v2 `resources` parsing | All supported v2 packages have native `package.toml` equivalents and clean migration reports. |",
        "| `app_install`, `app_upgrade`, `app_remove` script execution | Native catalogue entries route through signed `package.plan`/`package.reconcile`; legacy entries remain explicitly marked. |",
        "",
        "The VM test must therefore cover both classes: the checked-in native example through the resource engine, and `nostrhost-test` through the compatibility path until its native replacement is published and exercised.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    sys.stdout.write(render(args.root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
